version: '3.8'
networks:
  my-company.com:
services:
  ldap:
    container_name: ldap
    hostname: ldap.my-company.com
    build: ./ldap
    environment:
      - LDAP_ORGANISATION="My Company Inc."
      - LDAP_DOMAIN=my-company.com
      - LDAP_ADMIN_PASSWORD=Admin123
      - LDAP_BACKUP_CONFIG_CRON_EXP="* * * * *"
      - LDAP_BACKUP_DATA_CRON_EXP="*/5 * * * *"
      - LDAP_BACKUP_TTL=7
    ports:
      - "389:389"
      - "636:636"
    networks: [my-company.com]
  ldap-admin:
    image: osixia/phpldapadmin:0.9.0
    container_name: ldap-admin
    hostname: ldap-admin
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap
    ports:
      - "6443:443"
    depends_on:
      - ldap
    networks: [my-company.com]
